---
- hosts: localhost
  become: true

  tasks:
  - name: Ensure Chroney
    dnf:
      name: chrony
      state: present

  - name: Ensure chrony is running
    service:
       name: chronyd
       state: started
       enabled: yes
